version: '3.8'

services:
  certbot:
    image: certbot/certbot
    entrypoint: /bin/sh -c '/srv/app/site-reliability-tools/security/certbot.sh'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow access to Docker daemon
      - certbot_config:/etc/letsencrypt
      - /srv/.ssh/:/srv/.ssh
      - /srv/docker/certs/www/certbot:/var/www/certbot
      - /srv/app/site-reliability-tools/security/certbot.sh:/srv/app/site-reliability-tools/security/certbot.sh:rw
    secrets:
      - app_config
    networks:
      - portfolio-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  portfolio-network:
    external: true

volumes:
  certbot_config:
    external: true

secrets:
  app_config:
    external: true
