name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  validate-docker-compose:
    name: Validate Docker Compose Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo chmod +x /usr/local/bin/docker-compose

      - name: Validate Docker Compose Files
        run: |
          docker-compose -f maintenance/docker-compose.yml config
          docker-compose -f security/docker-compose.local.yml config

  deploy-docker-compose:
    name: Deploy Docker Compose Files
    runs-on: ubuntu-latest
    needs: validate-docker-compose
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure SSH key is available
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check SSH connection
        run: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'echo "SSH connection successful"'

      - name: Check for changes in security folder
        id: security_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^sre-app/security/'; then
            echo "security_changed=true" >> $GITHUB_ENV
          else
            echo "security_changed=false" >> $GITHUB_ENV
          fi

      - name: Check for changes in maintenance folder
        id: maintenance_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^sre-app/maintenance/'; then
            echo "maintenance_changed=true" >> $GITHUB_ENV
          else
            echo "maintenance_changed=false" >> $GITHUB_ENV
          fi

      - name: Deploy security folder changes
        if: env.security_changed == 'true'
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 \
              sre-app/security/certbot.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/security/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 \
              sre-app/security/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/security/

      - name: Deploy maintenance folder changes
        if: env.maintenance_changed == 'true'
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 \
<<<<<<< Updated upstream
              maintenance/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/maintenance/
=======
              sre-app/maintenance/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/maintenance/

      - name: Update Docker Swarm service
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
              'docker stack deploy -c /srv/app/site-reliability-tools/security/docker-compose.yml -c /srv/app/site-reliability-tools/maintenance/docker-compose.yml hosted-apps'
>>>>>>> Stashed changes
